-- begin CUBATRAINING_INDIVIDUAL
alter table CUBATRAINING_INDIVIDUAL add constraint FK_CUBATRAINING_INDIVIDUAL_ON_ID foreign key (ID) references CUBATRAINING_CUSTOMER(ID) on delete CASCADE^
-- end CUBATRAINING_INDIVIDUAL
-- begin CUBATRAINING_COMPANY
alter table CUBATRAINING_COMPANY add constraint FK_CUBATRAINING_COMPANY_ON_ID foreign key (ID) references CUBATRAINING_CUSTOMER(ID) on delete CASCADE^
create unique index IDX_CUBATRAINING_COMPANY_UNIQ_INN on CUBATRAINING_COMPANY (INN)^
-- end CUBATRAINING_COMPANY
