create unique index IDX_CUBATRAINING_CITY_UK_NAME on CUBATRAINING_CITY (NAME) where DELETE_TS is null ;
create unique index IDX_CUBATRAINING_CITY_UK_CODE on CUBATRAINING_CITY (CODE) where DELETE_TS is null ;
create index IDX_CUBATRAINING_CITY on CUBATRAINING_CITY (NAME);
